name: Release

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  publish-crate:
    needs: upload-assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Extra
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig

      - name: Publish
        run: cargo +stable publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
