name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "[0-9]+.*"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ${{ matrix.os }}
    name: upload-assets (${{ matrix.target }})

    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: sxtetris
          target: ${{ matrix.target }}
          build-tool: cargo
          token: ${{ secrets.GITHUB_TOKEN }}
          archive: $bin-$tag-$target
          include: LICENSE,README.md

  publish-crate:
    needs: upload-assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}

      - name: Publish
        run: cargo +stable publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
